name: publish-prerelease

on:
  workflow_call:

jobs:
  checkout:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: |
          npm install
          npm test
      - name: Update your package.json with an npm pre-release version
        id: pre-release-version
        uses: adobe/update-prerelease-npm-version@v1.2.0
        with:
          pre-release-tag: ${{ github.event.inputs.pre-release-tag }}
          dependencies-to-update: ${{ github.event.inputs.dependencies-to-update }}
          dependencies-to-update-version-tag: ${{ github.event.inputs.dist-tag }}
      - run: echo pre-release-version - ${{ steps.pre-release-version.outputs.pre-release-version }}           
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
          tag: ${{ github.event.inputs.dist-tag }}
          access: 'public'
